name: notify-discord

on:
  push:
    branches:
      - main
    paths:
      - '4k.md'
      - '4k-experimental.md'
      - '4k-sdcards.md'
      - '5x.md'
      - '5x-experimental.md'

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Wait for pages-build-deployment Workflow to Complete
        run: python3 check_workflow_status.py --workflow "pages build and deployment with artifacts-next"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Updated Files
        id: files
        run: |
          echo "files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -e '4k.md' -e '4k-experimental.md' -e '4k-sdcards.md' -e '5x.md' -e '5x-experimental.md')" >> $GITHUB_ENV

      - name: Run Script for Each Updated File
        run: |
          for file in ${{ env.files }}
          do
            echo "Processing $file"
            python3 common.py --target "$file"
          done
        env:
          WEBHOOK: ${{ secrets.RT4K_COMMUNITY_WEBHOOK }}

      - name: Commit and Push Changes
        run: |
          git diff --quiet || CHANGED=$?
          if [ "$CHANGED" == "1" ]; then
            sleep 15s
            git pull
            git config --local user.name "github-actions[bot]"
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Update firmware documentation"
            git push
          else
            echo "No changes to commit."
          fi
